# version = "0.1.6"
text:
  # RGB colour for text
  red: 255
  green: 200
  blue: 155

back:
  # RGB colour for shadow or outline
  red: 0
  green: 0
  blue: 0
  
display:
  # Whether to leave last payed on display when stopped, or
  # display splash screen
  # 0 = leave last played
  # 1 = display splash
  splash: 0
  
buttons:
  #declare the gpio pins for button actions
  #These 4 pins were chosen to prevent conflict with spi and DACs
  #other pis can be used if there is no conflict
  #text button loggles text on/off
  #pause toggles pause/play
  #next goes to next track if playing from library ot playlist
  #prev goes to previous track if playing from library ot playlist
  text: 6
  pause: 12
  next: 4
  prev: 5

# if True each screen update will be appended to the file 'moode_9341_fb.log' in the script directory
# the format of each change appended is
# date time: title - artist - album/station: state (play|pause|stop)
# view the log file with 'cat ~/moode_9341_fb/moode_9341_fb.log'
log: False